services:
  - type: web
    name: ticket-twig
    env: docker
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y php8.2 php8.2-cli php8.2-common php8.2-mbstring php8.2-xml php8.2-curl composer
      composer install --no-dev
    startCommand: php -S 0.0.0.0:10000 -t public
