services:
  - type: web
    name: tickettwig
    env: php
    plan: free
    buildCommand: "composer install --no-dev"
    startCommand: "php -S 0.0.0.0:8080 -t public"
    envVars:
      - key: PHP_VERSION
        value: "8.3"
